"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.string_bandpass_warning = exports.number_canvas_height = exports.number_canvas_width = exports.number_logo_height = exports.number_logo_width = exports.string_loadFromRepository = exports.string_createFromFile = exports.string_createFromScratch = exports.string_logo_img_micro_bk = exports.string_logo_img_cell_bk = exports.string_logo_img_no_bk = exports.string_json_ext = exports.string_maxNumberOf_identifier = exports.string_minNumberOf_identifier = exports.string_currentNumberOf_identifier = exports.string_linkedFields = exports.string_toolbar = exports.string_canvas = exports.string_array = exports.string_object = exports.string_enumNames = exports.string_enum = exports.string_default = exports.string_not_assigned = exports.string_na = exports.bool_isSettings = exports.bool_isDebug = void 0;
var bool_isDebug = false;
exports.bool_isDebug = bool_isDebug;
var bool_isSettings = false;
exports.bool_isSettings = bool_isSettings;
var string_na = "na";
exports.string_na = string_na;
var string_not_assigned = "Not assigned";
exports.string_not_assigned = string_not_assigned;
var string_default = "default";
exports.string_default = string_default;
var string_enum = "enum";
exports.string_enum = string_enum;
var string_enumNames = "enumNames";
exports.string_enumNames = string_enumNames;
var string_object = "object";
exports.string_object = string_object;
var string_array = "array";
exports.string_array = string_array;
var string_canvas = "canvas";
exports.string_canvas = string_canvas;
var string_toolbar = "toolbar";
exports.string_toolbar = string_toolbar;
var string_linkedFields = "LinkedFields";
exports.string_linkedFields = string_linkedFields;
var string_currentNumberOf_identifier = "Number_Of_";
exports.string_currentNumberOf_identifier = string_currentNumberOf_identifier;
var string_minNumberOf_identifier = "Min_Number_Of_";
exports.string_minNumberOf_identifier = string_minNumberOf_identifier;
var string_maxNumberOf_identifier = "Max_Number_Of_";
exports.string_maxNumberOf_identifier = string_maxNumberOf_identifier;
var string_json_ext = ".json";
exports.string_json_ext = string_json_ext;
var string_logo_img_no_bk = "MicroMetaApp_noBkg_3.png";
exports.string_logo_img_no_bk = string_logo_img_no_bk;
var string_logo_img_cell_bk = "MicroMetaApp_cellBkg.png";
exports.string_logo_img_cell_bk = string_logo_img_cell_bk;
var string_logo_img_micro_bk = "MicroMetaApp_TESMBkg_2.png";
exports.string_logo_img_micro_bk = string_logo_img_micro_bk;
var string_createFromScratch = "Create from scratch";
exports.string_createFromScratch = string_createFromScratch;
var string_createFromFile = "Load from file";
exports.string_createFromFile = string_createFromFile;
var string_loadFromRepository = "Load from repository";
exports.string_loadFromRepository = string_loadFromRepository;
var number_logo_width = 800;
exports.number_logo_width = number_logo_width;
var number_logo_height = 280;
exports.number_logo_height = number_logo_height;
var number_canvas_width = 2377;
exports.number_canvas_width = number_canvas_width;
var number_canvas_height = 969;
exports.number_canvas_height = number_canvas_height;
var string_bandpass_warning = "If you modify the number of band-pass, the information not saved are going to be lost!";
exports.string_bandpass_warning = string_bandpass_warning;